services:
  database:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgresData:/var/lib/postgresql/data

  tanatloc:
    image: tanatloc/tanatloc:${TANATLOC_TAG}
    restart: always
    depends_on:
      - database
    environment:
      - USER=${USER}
      - UID=${UID}
      - GID=${GID}
      - DB_ADMIN=postgres
      - DB_ADMIN_PASSWORD=${DATABASE_PASSWORD}
      - DB_HOST=database
      - DB_PORT=5432
      - DOMAIN=${DOMAIN}
      - ADDITIONAL_PATH=${ADDITIONAL_PATH}
      - HOST_STORAGE=${STORAGE_PATH}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - SHARETASK_JVM=${SHARETASK_JVM}
    volumes:
      - type: ${STORAGE_TYPE}
        source: ${STORAGE_PATH}
        target: /home/app/tanatloc

  network:
    image: nginx:1.23
    restart: always
    depends_on:
      - tanatloc
    ports:
      - "${NGINX_HTTP}:80"
      - "${NGINX_HTTPS}:443"
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
    volumes:
      - ./docker/run.nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  postgresData:
  tanatlocData:
