services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    # TO OPEN DATABASE TO HOST
    # ports:
    # - 5432:5432
    volumes:
      - postgresData:/var/lib/postgresql/data

  tanatloc:
    image: tanatloc/tanatloc:latest
    depends_on:
      - database
    environment:
      - DB_ADMIN=postgres
      - DB_ADMIN_PASSWORD=password
      - DB_HOST=database
      - DB_PORT=5432
    volumes:
      - tanatlocData:/root/tanatloc

  network:
    image: nginx:latest
    depends_on:
      - tanatloc
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/run.nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  postgresData:
  tanatlocData:
