services:
  database:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgresData:/var/lib/postgresql/data

  tanatloc:
    image: tanatloc/tanatloc:${TANATLOC_TAG}
    restart: always
    depends_on:
      - database
    environment:
      - DB_ADMIN=postgres
      - DB_ADMIN_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=database
      - DB_PORT=5432
      - DOMAIN=${DOMAIN}
    volumes:
      - type: ${STORAGE_TYPE}
        source: ${STORAGE_PATH}
        target: /root/tanatloc

  network:
    image: nginx:1.21
    restart: always
    depends_on:
      - tanatloc
    ports:
      - "${NGINX_HTTP}:80"
      - "${NGINX_HTTPS}:443"
    volumes:
      - ./docker/run.nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  postgresData:
  tanatlocData:
