services:
  database:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgresData:/var/lib/postgresql/data

  tanatloc:
    image: tanatloc/tanatloc:latest
    restart: always
    depends_on:
      - database
    environment:
      - DB_ADMIN=postgres
      - DB_ADMIN_PASSWORD=password
      - DB_HOST=database
      - DB_PORT=5432
      - DOMAIN=${DOMAIN}
    volumes:
      - type: volume
        source: tanatlocData
        target: /root/tanatloc

  network:
    image: nginx:1.21
    restart: always
    depends_on:
      - tanatloc
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/run.nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  postgresData:
  tanatlocData:
